# Generated by Django 5.1.6 on 2025-03-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'verbose_name': 'خبرنامه', 'verbose_name_plural': 'خبرنامه ها'},
        ),
    ]
