# Generated by Django 5.1.6 on 2025-03-05 23:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('description', models.TextField(verbose_name='توضیح دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام مهندس')),
                ('Occupation', models.CharField(default='مهندس عمران', max_length=50, verbose_name='رسته شغلی')),
                ('image', models.ImageField(upload_to='Project/ProjectEngineer/', verbose_name='تصویر مهندس')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان پروژه')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پروژه ')),
                ('area', models.CharField(max_length=50, verbose_name='مساحت پروژه')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2025, 3, 6, 2, 37, 40, 51332), verbose_name='زمان شروع')),
                ('infrastructure', models.IntegerField(default=0, verbose_name='زیربنا')),
                ('Financial_value', models.IntegerField(verbose_name='ارزش مالی')),
                ('Project_location', models.CharField(max_length=50, verbose_name='مکان پروژه')),
                ('content', models.TextField(verbose_name='متن پروژه')),
                ('categories', models.ManyToManyField(to='projects.category', verbose_name='دسته پروژه')),
                ('Project_engineer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.projectengineer', verbose_name='مهندس پروژه')),
            ],
            options={
                'verbose_name': 'پروژه ',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
