# Generated by Django 5.1.4 on 2025-03-10 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectengineer',
            options={'verbose_name': 'مهندس ', 'verbose_name_plural': 'مهندسین'},
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/', verbose_name='تصویر پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, to='projects.category', verbose_name='دسته پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد پروژه '),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 29, 55, 469125), verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='projectengineer',
            name='image',
            field=models.ImageField(upload_to='ProjectEngineer/', verbose_name='تصویر مهندس'),
        ),
    ]
