# Generated by Django 5.1.4 on 2025-03-10 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectengineer_options_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 16, 34, 19, 274828), verbose_name='زمان شروع'),
        ),
    ]
