# Generated by Django 5.1.6 on 2025-03-10 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 17, 40, 49, 514733), verbose_name='زمان شروع'),
        ),
    ]
