# Generated by Django 5.1.6 on 2025-03-10 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 1, 1, 20, 997029), verbose_name='زمان شروع'),
        ),
    ]
