# Generated by Django 5.1.6 on 2025-03-19 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 21, 50, 43, 609118), verbose_name='زمان شروع'),
        ),
    ]
