# Generated by Django 5.1.6 on 2025-03-21 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 9, 18, 7, 353875), verbose_name='زمان شروع'),
        ),
    ]
