# Generated by Django 5.1.6 on 2025-03-22 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 0, 55, 51, 440672), verbose_name='زمان شروع'),
        ),
    ]
