# Generated by Django 5.1.6 on 2025-03-22 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 1, 50, 6, 666292), verbose_name='زمان شروع'),
        ),
    ]
