# Generated by Django 5.1.6 on 2025-03-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectengineer',
            name='post',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='projects'),
            preserve_default=False,
        ),
    ]
