# Generated by Django 5.1.6 on 2025-03-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_projectengineer_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Project_engineer',
        ),
    ]
