# Generated by Django 5.1.6 on 2025-03-22 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('comments', '0003_alter_comment_author_alter_comment_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.blog', verbose_name='مقاله'),
        ),
    ]
