# Generated by Django 5.1.6 on 2025-03-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='templates/default-avatar.jpg', upload_to='comment_users_image/', verbose_name='تصویر کاربر'),
        ),
    ]
