# Generated by Django 5.1.6 on 2025-03-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.CharField(blank=True, default='مشتری', max_length=50, verbose_name='حرفه'),
        ),
    ]
