# Generated by Django 5.1.6 on 2025-03-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='templates/default-avatar.jpg', upload_to='comment_users_image/', verbose_name='تصویر کاربر'),
        ),
    ]
