# Generated by Django 5.1.4 on 2025-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="برای ست کردن آیکون، لطفاً نام کلاس آیکون را وارد کنید. برای مثال: 'fa-solid fa-code' برای FontAwesome یا 'material-icons code' برای Google Icons. اگر به دنبال آیکون هستید، می\u200cتوانید از لینک\u200cهای زیر استفاده کنید: <a href='https://fontawesome.com/icons' target='_blank'>FontAwesome</a> یا <a href='https://material.io/resources/icons/' target='_blank'>Google Icons</a>", max_length=100)),
            ],
            options={
                'verbose_name': 'سرویس ',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
    ]
