# Generated by Django 5.1.4 on 2025-03-10 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('description', models.TextField(verbose_name='توضیح دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان مقاله')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد مقاله ')),
                ('image', models.ImageField(null=True, upload_to='article/', verbose_name='تصویر مقاله')),
                ('content', models.TextField(verbose_name='متن مقاله')),
                ('categories', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
